[package]
name = "r_lambda_calculus"
version = "0.1.0"
authors = ["andy <andyyu2004@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "5.0.0"


